language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - postgresql

env:
  - DJANGO="django>=1.11,<1.12"
  - DJANGO="django>=2.0,<2.1"
  - DJANGO="django>=2.1,<2.2"

before_install:
  - pip install -q $DJANGO

install:
  - python setup.py develop
  - pip install .
  - pip install requests-mock mock pytest coveralls
  - pip install -q $DJANGO

script:
  - env
  - env PYTHONPATH=`pwd` coverage run --source=hordak ./manage.py test hordak

after_success:
  coveralls

addons:
  postgresql: "9.5"

matrix:
  exclude:
    - python: "3.4"
      env: DJANGO="django>=2.0,<2.1"
    - python: "3.4"
      env: DJANGO="django>=2.1,<2.2"

  allow_failures:
    - env: DJANGO="django>=2.1,<2.2"
